spring:
  datasource:
    password: admin
    url: jdbc:postgresql://localhost:5432/registration
    username: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true


server:
  port: 8082

ApartmentManagementController:
  addApartment: Authenticates user and returns its JWT token.
  deleteApartment: Creates user and returns its JWT token
  getAllApartments: Deletes specific user by username
  getApartmentById: Returns specific user by username